export const variantsTexts = {
  subTitle: {
    marginBottom: { base: '12px' },
    fontWeight: { base: '700' },
    fontSize: { base: '18px' },
  },
  labelInput: {
    fontSize: 16,
    fontWeight: '400',
    fontStyle: 'normal',
    textAlign: 'left',
    margin: 0,
    marginBottom: '8px',
    display: 'flex',
    fontFamily: 'revert',
    color: 'mirage',
    fontStretch: 'normal',
    letterSpacing: 'normal',
    lineHeight: '19px',
  },
  title: {
    fontSize: 32,
    color: 'white',
    fontFamily: 'DM Serif Display',
    fontWeight: '400',
    fontStyle: 'normal',
    lineHeight: { base: '44px' },
  },
  white50: {
    fontFamily: 'Lato',
    fontSiz3: '18px',
    color: 'white',
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: '22px',
    opacity: '50%',
  },
  whiteNormal: {
    fontFamily: 'Lato',
    fontSiz3: '18px',
    color: 'white',
    fontWeight: '700',
  },
};
